import crypto from "crypto";
import fs from "fs";
import path from "path";
import { createWorker } from "tesseract.js";
import Record from "../models/Record.js";

const fsPromises = fs.promises;

// ==========================================
// 🧠 FINE-TUNED EXTRACTION ENGINE
// ==========================================
const extractDataFromText = (text) => {
  let name = "Nil";
  let email = "Nil";
  let phone = "Nil";
  let location = "Nil";
  let college = "Nil";
  let department = "Nil";
  let platform = "Nil";

  // 🛑 BUG FIX 1: Prevent destroying newlines. 
  // Used [ \t]+ instead of \s+ to condense horizontal spaces while keeping \n
  const cleanedText = text
    .replace(/[\u200B-\u200D\uFEFF|~*^_{}[\]\\]/g, ' ')
    .replace(/[ \t]+/g, ' ') 
    .trim();
    
  const lowerText = cleanedText.toLowerCase();
  
  // Now this will actually split lines properly instead of creating one massive line
  const lines = cleanedText.split(/\r?\n/).map(line => line.trim()).filter(line => line.length > 2);
  
  // Create a flat text version for regexes that shouldn't care about line breaks (Email, Phone, Location)
  const flatText = cleanedText.replace(/\r?\n/g, ' '); 

  // 1. Phone
  const phoneRegex = /(?<!\d)(?:\+?91[\s-]?)?([6-9]\d{9})\b/;
  const phoneMatch = flatText.match(phoneRegex);
  if (phoneMatch) phone = phoneMatch[1]; 

  // 2. Email
  const emailRegex = /\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,8}\b/;
  const emailMatch = flatText.match(emailRegex);
  if (emailMatch) email = emailMatch[0].toLowerCase();

  // 3. Platform
  if (/\bnaukri\b/i.test(lowerText)) platform = "Naukri";
  else if (/\bshine\b/i.test(lowerText)) platform = "Shine";
  else if (/\blinkedin\b/i.test(lowerText)) platform = "LinkedIn";
  else if (/\bfoundit\b|\bmonster\b/i.test(lowerText)) platform = "Foundit";
  else if (/\bindeed\b/i.test(lowerText)) platform = "Indeed";

  // 4. Location
  const techHubs = ["chennai", "omr", "sholinganallur", "perungudi", "tidel park", "bangalore", "hyderabad", "pune", "mumbai", "coimbatore"];
  for (const city of techHubs) {
    if (new RegExp(`\\b${city}\\b`, 'i').test(flatText)) {
      location = city.length <= 3 ? city.toUpperCase() : city.charAt(0).toUpperCase() + city.slice(1);
      break;
    }
  }

  // 5. COLLEGE & DEPARTMENT CLEANER (FIXED)
  const uiGarbage = ["fresher", "chennai", "modified", "active", "yesterday", "v", "e", "u", "s", "no comments", "save", "print"];
  
  for (const line of lines) {
    const lowerLine = line.toLowerCase();
    
    // Check if line contains college/university keywords
    if (/(university|college|institute|academy)/i.test(lowerLine)) {
      // Step A: Remove UI garbage words from this line first
      let cleanLine = line;
      uiGarbage.forEach(word => {
         const re = new RegExp(`\\b${word}\\b`, 'gi');
         // Replace with space so words don't get mashed together
         cleanLine = cleanLine.replace(re, " "); 
      });
      
      // Step B: Split Degree/Dept
      const degreePattern = /(B\.?C\.?A|B\.?Sc|B\.?Tech|B\.?E|M\.?C\.?A|M\.?B\.?A|M\.?Sc|B\.?A|B\.?Com)/i;
      const match = cleanLine.match(degreePattern);
      
      if (match) {
        department = match[0].toUpperCase().replace(/\./g, '');
        cleanLine = cleanLine.replace(match[0], "").replace(/[:\-]/g, "").trim();
      } else {
        cleanLine = cleanLine.replace(/[:\-]/g, "").trim();
      }

      // 🛑 BUG FIX 2: Targeted extraction so we don't accidentally grab a massive string
      // Isolates 5 to 60 chars ending in the keyword, plus an optional "of Technology/Arts"
      const targetedCollegeMatch = cleanLine.match(/([a-zA-Z.\s&]{5,60}\b(?:College|University|Institute|Academy)\b(?:\s+of\s+[a-zA-Z.\s&]+)?)/i);
      
      if (targetedCollegeMatch) {
        college = targetedCollegeMatch[1].trim();
      } else {
        // Fallback: If line is overly long, clip it so the UI doesn't break
        college = cleanLine.length > 70 ? cleanLine.substring(0, 70) + "..." : cleanLine;
      }
      
      break; // Found our college line
    }
  }

  // 6. IMPROVED NAME SPLITTER
  if (email !== "Nil") {
    const emailPrefix = email.split('@')[0];
    let nameParts = emailPrefix.replace(/[0-9]/g, '').replace(/[._-]/g, ' ').trim();
    
    if (!nameParts.includes(' ')) {
        nameParts = nameParts.replace(/([a-z])([A-Z])/g, '$1 $2');
    }
    
    name = nameParts.split(' ').map(w => w.charAt(0).toUpperCase() + w.slice(1)).join(' ');
  }

  // Clean up any double spaces generated by our replacements
  college = college.replace(/\s+/g, ' ').trim();

  return { 
    name: name || "Nil", 
    email, 
    phone, 
    location, 
    college: college.length > 5 ? college : "Nil", 
    department: department || "Nil", 
    platform 
  };
};

// ==========================================
// 🚀 MAIN UPLOAD CONTROLLER 
// ==========================================
export const processImages = async (req, res) => {
  try {
    const files = req.files;
    if (!files || files.length === 0) return res.status(400).json({ error: "No files uploaded." });

    const results = [];
    const duplicates = [];
    const worker = await createWorker('eng');

    try {
      for (const file of files) {
        const startTime = Date.now();
        const originalPath = path.resolve(file.path);

        try {
          const fileBuffer = await fsPromises.readFile(originalPath);
          const hash = crypto.createHash("sha256").update(fileBuffer).digest("hex");

          const existingRecord = await Record.findOne({ imageHash: hash }).lean();
          if (existingRecord) {
            duplicates.push(file.originalname);
            await fsPromises.unlink(originalPath).catch(() => {});
            continue; 
          }

          const { data: { text } } = await worker.recognize(originalPath);
          let extractedData = extractDataFromText(text);
          
          if (extractedData.name === "Nil") extractedData.name = file.originalname.split('.')[0]; 

          const loadingTime = ((Date.now() - startTime) / 1000).toFixed(2) + " sec";
          const newRecord = await Record.create({ imageHash: hash, ...extractedData, loadingTime });

          results.push(newRecord);
        } catch (err) {
          console.error(`Error: ${file.originalname}`, err);
        } finally {
          await fsPromises.unlink(originalPath).catch(() => {});
        }
      }
    } finally {
      await worker.terminate();
    }

    res.status(200).json({ processed: results, duplicates });
  } catch (err) {
    res.status(500).json({ error: "Server Error." });
  }
};